# Generated by Django 4.2.2 on 2023-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_mobile', models.CharField(max_length=25, verbose_name='Telefon raqam shaxsiy')),
                ('phone_clinica', models.CharField(max_length=25, verbose_name='Telefon raqam clinica')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email sissilka')),
                ('adress_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name="Manzil so'z bilan o'zbek tilida")),
                ('adress_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name="Manzil so'z bilan rus tilida")),
                ('adress_en', models.CharField(blank=True, max_length=256, null=True, verbose_name="Manzil so'z bilan ingliz tilida")),
                ('instagramm', models.CharField(blank=True, max_length=256, null=True, verbose_name='Instagram sissilka')),
                ('telegram', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telegram sissilka')),
                ('facebook', models.CharField(blank=True, max_length=256, null=True, verbose_name='Facebook sissilka')),
                ('twitter', models.CharField(blank=True, max_length=256, null=True, verbose_name='Twitter sissilka')),
                ('odnoklassniki', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ok.ru sissilka')),
                ('youtube', models.CharField(blank=True, max_length=256, null=True, verbose_name='YOUTUBE sissilka')),
                ('locatsiya', models.CharField(blank=True, max_length=256, null=True, verbose_name='Locatsiya sissilka')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=128, verbose_name="Ismi o'zbek tilida")),
                ('first_name_uz', models.CharField(max_length=128, verbose_name="Familiyasi o'zbek tilida")),
                ('middle_name_uz', models.CharField(max_length=128, verbose_name="Otasini ismi o'zbek tilida")),
                ('name_ru', models.CharField(max_length=128, verbose_name='Ismi rus')),
                ('first_name_ru', models.CharField(max_length=128, verbose_name='Familiyasi rus tilida')),
                ('middle_name_ru', models.CharField(max_length=128, verbose_name='Otasini ismi rus tilida')),
                ('name_en', models.CharField(max_length=128, verbose_name='Ismi ingliz tilida')),
                ('first_name_en', models.CharField(max_length=128, verbose_name='Familiyasi ingliz tildia')),
                ('middle_name_en', models.CharField(max_length=128, verbose_name='Otasini ismi ingliz tilida')),
                ('specialty_uz', models.CharField(max_length=256, verbose_name="Mutaxassisligi o'zbek tilida")),
                ('specialty_ru', models.CharField(max_length=256, verbose_name='Mutaxassisligi rus tilida')),
                ('specialty_en', models.CharField(max_length=256, verbose_name='Mutaxassisligi ingliz tilida')),
                ('about_doctor_uz', models.TextField(verbose_name="Shifokor haqida o'zbek tilida")),
                ('about_doctor_ru', models.TextField(verbose_name='Shifokor haqida rus tilida')),
                ('about_doctor_en', models.TextField(verbose_name='Shifokor haqida ingliz tilida')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Shaxsiy Telefon raqam')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Shaxsiy Email sissilka')),
                ('instagramm', models.CharField(blank=True, max_length=256, null=True, verbose_name='Shaxsiy Instagram sissilka')),
                ('telegram', models.CharField(blank=True, max_length=256, null=True, verbose_name='Shaxsiy Telegram sissilka')),
                ('facebook', models.CharField(blank=True, max_length=256, null=True, verbose_name='Shaxsiy Facebook sissilka')),
                ('twitter', models.CharField(blank=True, max_length=256, null=True, verbose_name='Shaxsiy Twitter sissilka')),
                ('odnoklassniki', models.CharField(blank=True, max_length=256, null=True, verbose_name='Shaxsiy Ok.ru sissilka')),
                ('img', models.ImageField(upload_to='', verbose_name="Shifokor sur'ati")),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Yangilikga oid rasm')),
                ('title_uz', models.CharField(max_length=512, verbose_name="Yangilikning Sarlavhasi o'zbek tilida")),
                ('title_ru', models.CharField(max_length=512, verbose_name='Yangilikning Sarlavhai rus tilida')),
                ('title_en', models.CharField(max_length=512, verbose_name='Yangilikning Sarlavha ingliz tilida')),
                ('short_desc_uz', models.TextField(verbose_name="Yangilikning Qisqa ma'lumoti o'zbek tilida")),
                ('short_desc_ru', models.TextField(verbose_name="Yangilikning Qisqa ma'lumoti rus tilida")),
                ('short_desc_en', models.TextField(verbose_name="Yangilikning Qisqa ma'lumoti ingliz tilida")),
                ('desc_uz', models.TextField(verbose_name="Yangilikning To'liq ma'lumoti o'zbek tilida")),
                ('desc_ru', models.TextField(verbose_name="Yangilikning To'liq ma'lumoti rus tilida")),
                ('desc_en', models.TextField(verbose_name="Yangilikning To'liq ma'lumoti ingliz tilida")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Yangilikni saytga joylash vaqti')),
            ],
        ),
    ]
