# Generated by Django 4.2.2 on 2023-07-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='new',
            name='short_desc_en',
        ),
        migrations.RemoveField(
            model_name='new',
            name='title_en',
        ),
    ]
