# Generated by Django 4.2.2 on 2023-07-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_remove_new_desc_en_remove_new_short_desc_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='img',
            new_name='image',
        ),
    ]
