# Generated by Django 4.2.2 on 2023-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_rename_img_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='image_sayt', verbose_name='Yangilikga oid rasm'),
        ),
    ]
