# Generated by Django 4.2.2 on 2023-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_alter_new_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='img',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=1, upload_to='image_sayt_doctors', verbose_name="Shifokor sur'ati"),
            preserve_default=False,
        ),
    ]
