# Generated by Django 4.2.2 on 2023-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0006_remove_doctor_img_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about_doctor_en',
            field=models.TextField(blank=True, null=True, verbose_name='Shifokor haqida ingliz tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about_doctor_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Shifokor haqida rus tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about_doctor_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Shifokor haqida o'zbek tilida"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Familiyasi ingliz tildia'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Familiyasi rus tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_uz',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Familiyasi o'zbek tilida"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otasini ismi ingliz tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otasini ismi rus tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name_uz',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Otasini ismi o'zbek tilida"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ismi ingliz tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ismi rus'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name_uz',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Ismi o'zbek tilida"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Mutaxassisligi ingliz tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Mutaxassisligi rus tilida'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Mutaxassisligi o'zbek tilida"),
        ),
    ]
