# Generated by Django 4.2.2 on 2023-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0007_alter_doctor_about_doctor_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
