# Generated by Django 4.2.2 on 2023-08-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0009_remove_doctor_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_clinica',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon raqam clinica'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon raqam shaxsiy'),
        ),
    ]
