# Generated by Django 4.2.2 on 2023-07-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoz',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Birinchi rasm'),
        ),
        migrations.AlterField(
            model_name='diagnoz',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ikkinchi rasm'),
        ),
    ]
