# Generated by Django 4.2.2 on 2023-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_diagnoz_image_one_alter_diagnoz_image_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=None),
        ),
    ]
