# Generated by Django 4.2.2 on 2023-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoz',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='image_diagnoz/', verbose_name='Birinchi rasm'),
        ),
        migrations.AlterField(
            model_name='diagnoz',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='image_diagnoz/', verbose_name='Ikkinchi rasm'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='document_patient/'),
        ),
    ]
