# Generated by Django 4.2.2 on 2023-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_diagnoz_image_one_alter_diagnoz_image_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoz',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izox'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name="Bemorning tug'ilgan yili"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izox'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Bemorning telefon raqami'),
        ),
        migrations.AlterField(
            model_name='retsep',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
