# Generated by Django 4.2.2 on 2023-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_diagnoz_comment_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoz',
            name='recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsiya'),
        ),
    ]
