# Generated by Django 4.2.2 on 2023-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_diagnoz_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoz',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
